"""add created_at and deleted_at to base

Revision ID: 1778023aa31a
Revises: fd271a5fa0c4
Create Date: 2026-05-03 23:00:11.930269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1778023aa31a'
down_revision: Union[str, Sequence[str], None] = 'fd271a5fa0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('applications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('attachments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key('fk_company_current_address', 'companies', 'addresses', ['current_address_id'], ['id'], use_alter=True)
    op.add_column('job_postings', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('reminders', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user_profiles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key('fk_user_current_address', 'user_profiles', 'addresses', ['current_address_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_current_address', 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'deleted_at')
    op.drop_column('reminders', 'deleted_at')
    op.drop_column('job_postings', 'deleted_at')
    op.drop_constraint('fk_company_current_address', 'companies', type_='foreignkey')
    op.drop_column('companies', 'deleted_at')
    op.drop_column('companies', 'created_at')
    op.drop_column('attachments', 'deleted_at')
    op.drop_column('applications', 'deleted_at')
    op.drop_column('applications', 'created_at')
    op.drop_column('addresses', 'deleted_at')
    # ### end Alembic commands ###
