"""add password_hash and username to user_profiles

Revision ID: a976895475a2
Revises: 430eb0f1aecc
Create Date: 2026-05-14 19:27:30.061206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a976895475a2'
down_revision: Union[str, Sequence[str], None] = '430eb0f1aecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_company_current_address', 'companies', 'addresses', ['current_address_id'], ['id'], use_alter=True)
    op.drop_column('job_postings', 'date_posted')
    op.add_column('user_profiles', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_unique_constraint(op.f('uq_user_profiles_username'), 'user_profiles', ['username'])
    op.create_foreign_key('fk_user_current_address', 'user_profiles', 'addresses', ['current_address_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_current_address', 'user_profiles', type_='foreignkey')
    op.drop_constraint(op.f('uq_user_profiles_username'), 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'username')
    op.drop_column('user_profiles', 'password_hash')
    op.add_column('job_postings', sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_company_current_address', 'companies', type_='foreignkey')
    # ### end Alembic commands ###
