"""add auth method check constraint

Revision ID: c6f3c33c1fbb
Revises: 859c0cc06079
Create Date: 2026-07-09 18:24:25.306576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f3c33c1fbb'
down_revision: Union[str, Sequence[str], None] = '859c0cc06079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_company_current_address', 'companies', 'addresses', ['current_address_id'], ['id'], use_alter=True)
    op.add_column('user_profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(op.f('uq_user_profiles_email'), 'user_profiles', ['email'])
    op.create_foreign_key('fk_user_current_address', 'user_profiles', 'addresses', ['current_address_id'], ['id'], use_alter=True)
    op.create_check_constraint(
        'ck_user_profiles_has_auth_method',
        'user_profiles',
        "(email IS NOT NULL AND password IS NOT NULL) "
        "OR (auth_provider IS NOT NULL AND auth_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_user_profiles_has_auth_method', 'user_profiles', type_='check')
    op.drop_constraint('fk_user_current_address', 'user_profiles', type_='foreignkey')
    op.drop_constraint(op.f('uq_user_profiles_email'), 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'password')
    op.drop_column('user_profiles', 'email')
    op.drop_constraint('fk_company_current_address', 'companies', type_='foreignkey')
    # ### end Alembic commands ###
